/**
 * Which articles are the entry point.
 *
 * The corpus is two rings: cities, and what cities need explained. Nothing in
 * a document says which it is — a city and a deity are both just documents —
 * so the split is written down here, generated from the title list the import
 * used, and dropped into the site as a `.yaml` the entry document can query
 * like any other record.
 */
import {readFile, writeFile} from 'node:fs/promises'
import YAML from 'yaml'
import {defaultResolve} from 'mdy-docs/parse/wiki.js'

const titles = (await readFile('pipeline/city-titles.txt', 'utf8'))
  .split('\n')
  .map((t) => t.trim())
  .filter(Boolean)

const slugs = titles.map((t) => defaultResolve(t).replace(/^\/+/, '')).sort()

await writeFile(
  'site/cities.yaml',
  YAML.stringify({
    about:
      'The corpus core: places. Everything else in the corpus is here because a ' +
      'city needed it explained. Generated by pipeline/mark-core.mjs.',
    count: slugs.length,
    cities: slugs
  })
)

console.log(`${slugs.length} cities marked as the core`)
